spring.application.name=agrotech
# ===============================
# CONFIGURACI?N DEL SERVIDOR
# ===============================
server.port=8080
server.servlet.context-path=/

# ===============================
# POSTGRESQL 16 (Relacional)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/agrotech_cj
spring.datasource.username=postgres
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# MONGODB 7.0 (Time-Series)
# ===============================
spring.data.mongodb.uri=mongodb://localhost:27017/agrotech_telemetria
# Si tu mongo local tiene credenciales: mongodb://user:pass@localhost:27017/agrotech_telemetria

# ===============================
# OPEN-METEO (Variables de entorno/simulaci?n)
# ===============================
openmeteo.api.url=https://api.open-meteo.com/v1/forecast
openmeteo.location.lat=6.15
openmeteo.location.lon=-75.37

# ===============================
# JWT CONFIGURATION
# ===============================
app.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposesOnly
app.jwt.expiration=86400000
